### ISSUE TITLE
Let's Encrypt SSL certifcates

### ISSUE THREAD

**Issue by LordChunk** [arugifa/simplelogin-postfix-docker#1]
### Question
The docker container seems to want to request an SSL certificate from Let's Encrypt, but it is not entirely clear to me what these are used for and which domain I should request them for. Are these certificates for your "email" domain or the domain from which you serve the web interface?

#### Example
If your standard emails are send from ``example.com`` and your Simplelogin app runs on ``app.example.com`` (like described in the SL documentation). Is this certificate meant for ``example.com`` or ``app.example.com``?

**Comment by arugifa** [comment]
Hi @LordChunk ,

Let's summarize how people would send you an email when you use Simple Login. I guess that you probably know most of it, but let's get into the details, so it's simpler to understand for which domain the Postfix container will generate a certificate:

1. someone wants to send you an email to your email address (e.g., `toto@example.com`), and uses for that his/her favorite email client,
2. after finishing to write the email, he/she clicks on **Send**, and the email client will look for the email server responsible for the domain of your email address (`example.com`),
2. after performing a DNS query, looking for the MX record of your email address domain, the client will see that the email server address is `mail.example.com`,
3. the client will send the email to `mail.example.com`, i.e., Simple Login Postfix server,
4. Postfix will finally forward the email to the Simple Login email handler.

In this scenario, the Postfix container is trying to generate a certificate for the step number **3**, i.e., for the MX record of your email domain, i.e., for the FQDN of the Postfix server itself (`mail.example.com`).

I hope it helps :smiley: If not, please let me know :wink: I will update the README to make it more clear :+1: :+1:
