### ISSUE TITLE
relayhost Postfix parameter

### ISSUE THREAD

**Issue by Metabaron1** [arugifa/simplelogin-postfix-docker#3]
Hi Arugifa
It may be usefull to have relayhost. So here is a pull request.  There should be absolutly no change to current deployment if RELAY_HOST variable parameter is not set in docker-compose.
This is my first pull request to Github, and also never used Python, so not sure if I have done everything correctly ;)

**Comment by Metabaron1** [comment]
Oh, and another improvement would be to change docker user from root, as it's a good practice to have a standard user running within docker container. This could be a security issue, specially for the front-end container to Internet as it is this Postfix container.
But unlike relayhost, this change would impact current deployment: container port (25/80) would be changed to > 1024, as only root can open port lower than 1024, so docker-compose should be changed to translate back  (like 25:1025, 80:1080).
Maybe next time in another PR.

And sorry for my bad english ;)

**Comment by arugifa** [comment]
Hi @Metabaron1 ,

Sorry for my late reply: I have been quite busy this week.

I will have a look to your Pull Request this weekend. Thanks for your contribution and feedback :smiley:

**Comment by Metabaron1** [comment]
Don't worry, I'm not in a hurry, it's just a hobby, usefull hoby ;)
By the way , I was wrong about changing Postfix user from root. I tried, but without success.
And finally I found a confirmation on Redhat support, it's not possible by Postfix design:
https://access.redhat.com/solutions/2743441
"The Postfix master process always needs to run as root, since it is the one spawning the rest of the Postfix daemons/processes."

So only maybe some day with in an official container designed for security from Postfix developpers.

**Comment by arugifa** [comment]
Fixed by #2 

Thanks again for your contribution @Metabaron1 :sunflower:

**Comment by arugifa** [comment]
@Metabaron1 The release **3.1.0-6**, which includes your change, has been successfully deployed to Docker Hub. Enjoy! :tada:

**Comment by Metabaron1** [comment]
I can't use it my self as i'm  running on arm64 arch, not Intel arch, but thanks for the Docker Hub image.
Btw if other users request for different arch image than amd64, I can submit a PR for multiarch Docker Hub autobuild :)

**Comment by arugifa** [comment]
Sure :+1: :+1: I didn't pay attention in fact that there was only one arch image available on Docker Hub.

**Comment by Metabaron1** [comment]
Then when/if needed, you can get the PR from this branch: [Multi-arch-patch](https://github.com/Metabaron1/simplelogin-postfix-docker/tree/Multi-arch-patch), /hooks directory + 1 multiarch Dockerfile, that can be applied to any repository.
It's inspired from this [repo](https://github.com/jnovack/docker-multi-arch-hooks), which I have replaced the multiple Dockerfile.arch, by a single Dockerfile.multiarch associated with a hooks/TARGET_ARCHS.txt arch parameter file.

It's an interesting concept that multiarch build based on [qemu](https://github.com/multiarch/qemu-user-static), I have learned something ;)
