### ISSUE TITLE
Typo in certbot-renew-crontab.sh

### ISSUE THREAD

**Issue by imro2** [arugifa/simplelogin-postfix-docker#5]
Line 8 has `cerbot` instead of `certbot`

**Comment by arugifa** [comment]
Hi @imro2 ,

Thanks a lot for spotting this error!

I released a fix, available with the tag `3.1.0-7` on [Docker Hub](https://hub.docker.com/layers/arugifa/simplelogin-postfix/3.1.0-7/images/sha256-9d07dd8a9cb7a48492fb2b0544253241ce836ae7d84a091f7d7c5af13b961148).

Have a very nice day :sun_with_face:
