### ISSUE TITLE
usage without let's encrypt and using smtp in container

### ISSUE THREAD

**Issue by FarisZR** [arugifa/simplelogin-postfix-docker#8]
hi!
i have another program handling certificates, can i use this image with pre made certs ?

also can i use smtp to send emails for other services in the server ?

**Comment by arugifa** [comment]
Hi @fareszr ,

1. This image can only run for now with Certbot to generate SSL certificates. It is running without SSL activated if certificates generation fails.
2. Do you have examples?

:rainbow:

**Comment by FarisZR** [comment]
> Hi @fareszr ,
> 
>     1. This image can only run for now with Certbot to generate SSL certificates. It is running without SSL activated if certificates generation fails.
unfortunately that's a deal breaker for me i need the ability to use custom certs

>     2. Do you have examples?
something like nextcloud

**Comment by arugifa** [comment]
> > ```
> > 2. Do you have examples?
> > ```
> 
> something like nextcloud

This Postfix image is tailored for SimpleLogin, and SimpleLogin only :wink:
